[package]
name = "notespace-editor"
version = "0.2.0"
edition = "2024"
license = "MIT"
authors = ["Nathan Laan"]

[dependencies]
iced = {version = "0.13.1", features = ["tokio", "advanced"] }
tokio = {version = "1.44", features = ["fs", "rt"]}
rfd = {version = "0.15"}
rust-iced-fa = "0.1.0"
fa-iced = "0.1.1"
